spring:
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5435/product_catalog_test_db}
    username: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5435/product_catalog_test_db}
    user: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:postgres}

logging:
  level:
    root: WARN
    com.telcox: DEBUG
