management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway



---
spring:
  config:
    activate:
      on-profile: k8s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.minikube.internal:9011/realms/telco-crm-realm/protocol/openid-connect/certs
          issuer-uri: http://host.minikube.internal:9011/realms/telco-crm-realm
