spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/billing_db
    username: telco_admin
    password: telco_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/billing_db
    user: telco_admin
    password: telco_password