server:
  port: 9004

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8888"
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    consumer:
      group-id: order-service
      auto-offset-reset: earliest



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0


app:
  kafka:
    topics:
      payment-completed: "telcox.payment.payment.PaymentCompleted"
      subscription-activated: "telcox.subscription.subscription.SubscriptionActivated"