server:
  port: 9008

spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"
  flyway:
    enabled: true
    baseline-on-migrate: true

