package com.telcocrm.common.core.constant;

/**
 * Canonical HTTP header names used across the platform. The gateway injects the
 * identity/correlation headers; downstream services read them (they never re-parse the JWT).
 */
public final class HeaderConstants {

    /** Correlation id propagated end-to-end. Injected/generated by the gateway. */
    public static final String CORRELATION_ID = "X-Correlation-Id";

    /** Authenticated user id, injected by the gateway after JWT validation. */
    public static final String USER_ID = "X-User-Id";

    /** Comma-separated roles of the authenticated user, injected by the gateway. */
    public static final String USER_ROLES = "X-User-Roles";

    /** Client-supplied key making POST operations idempotent (payment-service, order-service). */
    public static final String IDEMPOTENCY_KEY = "Idempotency-Key";

    private HeaderConstants() {
    }
}
