server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: ${CONFIG_SERVER_PROFILE:native}
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:${user.dir}/../config-repo/configs/{application}
            - file:${user.dir}/../config-repo/configs
            - file:${user.dir}/config-repo/configs/{application}
            - file:${user.dir}/config-repo/configs
            - classpath:/config-repo/configs/{application}
            - classpath:/config-repo/configs
        git:
          uri: ${GIT_CONFIG_REPO_URI:}
          username: ${GIT_CONFIG_USERNAME:}
          password: ${GIT_CONFIG_PASSWORD:}
          search-paths:
            - configs/{application}
            - configs
          default-label: ${GIT_CONFIG_LABEL:main}
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:eureka}@localhost:8761/eureka/
