apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: telco-crm
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: telcox/customer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:TieredStopAtLevel=1 -Xms128m -Xmx256m"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s" 
            - name: AES_GCM_KEY
              valueFrom:
                secretKeyRef:
                  name: customer-service-secret
                  key: AES_GCM_KEY
          resources:
            requests:
              memory: "192Mi"
              cpu: "200m"
            limits:
              memory: "384Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 180
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 180
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 20
