apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  namespace: telco-crm
type: Opaque
stringData:
  # Gerçek anahtarı production'da kubectl create secret ile elle oluşturun
  AES_GCM_KEY: "change-this-placeholder-key-in-prod"
