spring:
  kafka:
    bootstrap-servers: ${TEST_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    redis:
      host: ${TEST_REDIS_HOST:localhost}
      port: ${TEST_REDIS_PORT:6379}

management:
  tracing:
    sampling:
      probability: 0.0

logging:
  level:
    root: WARN
