server:
  port: 29005

spring:
  application:
    name: subscription-service
  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
