apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
  namespace: telco-crm
  labels:
    app: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: telcox/ticket-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9010
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:TieredStopAtLevel=1 -Xms128m -Xmx256m"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s" 
          resources:
            requests:
              memory: "192Mi"
              cpu: "200m"
            limits:
              memory: "384Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9010
            initialDelaySeconds: 180
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9010
            initialDelaySeconds: 180
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 20
