apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
  namespace: telco-crm
type: Opaque
stringData:
  # Gerçek anahtarı production'da kubectl create secret ile elle oluşturun
  KEYCLOAK_CLIENT_SECRET: "change-this-placeholder-secret-in-prod"
