apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: telco-crm
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
