spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/notification_db
  flyway:
    url: jdbc:postgresql://host.minikube.internal:5432/notification_db
